### PR TITLE
Added my name to Names.md

### PR DESCRIPTION
**Pull request by danielgitk**

### CODE REVIEW

**Comment by YiseBoge** [comment]
It is better to use a present imperative text for the commit message. sth like "Add abc to Names.md"

**Comment by YiseBoge** [comment]
Additionally, don't use pronouns as someone who see's this later on may not know what your name is

**Comment by YiseBoge** [comment]
Reviewers should also be assigned to the pull request as it is only allowed to merge once reviewers have approved it

**Comment by YiseBoge** [comment]
The instructions also say to add your name in SORTED order, so better to fix that too.

**Comment by danielgitk** [comment]
on it boss

**Pull request merged**
